version: '3'

includes:
  docker: ./taskfiles/Taskfile_docker.yaml
  
tasks:

  default:
    desc: lists all tasks
    silent: true
    cmds:
      - task --list-all
      - echo ""
      - echo "Example usage-> 'task check-virtualenv'"